//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AGENT()
        {
            this.ARRESTED = new HashSet<ARRESTED>();
        }
    
        public int id_agent { get; set; }
        public int id_Person_agent { get; set; }
        public System.DateTime hiredate { get; set; }
        public int job { get; set; }
        public int id_police_station { get; set; }
        public string job_phone_number { get; set; }
        public bool status { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        public virtual police_station police_station { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARRESTED> ARRESTED { get; set; }
    }
}
