//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT
    {
        public int id_contact { get; set; }
        public int id_person_contact { get; set; }
        public string type_of_relationship { get; set; }
        public int id__agent_contact { get; set; }
        public bool status { get; set; }
    
        public virtual PERSON PERSON { get; set; }
    }
}
