//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAMILY
    {
        public int id_family { get; set; }
        public int id_Person { get; set; }
        public string Tiporelacion { get; set; }
        public int id_arrested { get; set; }
        public bool status { get; set; }
    
        public virtual ARRESTED ARRESTED { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
