//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Crimenes
    {
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string dpi { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public System.DateTime date_of_capture { get; set; }
        public string crime { get; set; }
        public string description { get; set; }
    }
}
