//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vistaRequerida
    {
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string dpi { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public int id_department { get; set; }
        public string direccion { get; set; }
        public string notele { get; set; }
        public bool status { get; set; }
    }
}
